# azure-pipelines.yml for users-api

trigger:
  branches:
    include:
    - main # Or your default branch
# Removed paths filter as this is an independent repo

resources:
- repo: self

variables:
  # Agent VM image name
  vmImageName: 'ubuntu-latest'

  # Azure Container Registry connection details
  dockerRegistryServiceConnection: 'ACR-ingesoft5acrregistry-Connection' # Updated Service Connection Name
  acrLoginServer: 'ingesoft5acrregistry.azurecr.io' # Updated ACR Login Server
  imageRepository: 'users-api' # Name for the image in ACR
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
  buildContextPath: '$(Build.SourcesDirectory)'
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build and Push stage
  jobs:
  - job: Build
    displayName: Build and Push Users API image
    pool:
      vmImage: $(vmImageName)
    steps:
    # Optional: If your build requires Maven, uncomment and configure this step
    # - task: Maven@3
    #   displayName: 'Build JAR with Maven'
    #   inputs:
    #     mavenPomFile: '$(buildContextPath)/pom.xml'
    #     goals: 'package' # Or 'clean package'
    #     options: '-DskipTests=true' # Skip tests during pipeline build if needed
    #     publishJUnitResults: false # Set to true if you want to publish test results
    #     javaHomeOption: 'JDKVersion'
    #     jdkVersionOption: '1.17' # Or the Java version required by your project
    #     mavenVersionOption: 'Default'
    #     mavenOptions: '-Xmx3072m'
    #     mavenAuthenticateFeed: false
    #     effectivePomSkip: false
    #     sonarQubeRunAnalysis: false

    # Login to ACR
    - task: Docker@2
      displayName: Login to ACR
      inputs:
        command: login
        containerRegistry: $(dockerRegistryServiceConnection)

    # Build the image
    - task: Docker@2
      displayName: Build image
      inputs:
        command: build
        repository: $(imageRepository) # Build locally first
        dockerfile: $(dockerfilePath)
        buildContext: $(buildContextPath)
        arguments: '--no-cache' # Add this line to disable build cache
        tags: |
          $(tag)
          latest

    # Push the image
    - task: Docker@2
      displayName: Push image
      inputs:
        command: push
        repository: $(imageRepository) # Use the local image name built previously
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)
          latest
